### ISSUE TITLE
Broken debug mode in QtCreator

### ISSUE THREAD

**Issue by cezaryece** [fmanlou/qt6printers#2]
Sorry, you made great work, but after installing current qt6pronters QtCreator debug mode is completely broken, application just wont run and hangs with only startup command
"15:45:37: Debugging /app.run -qmljsdebugger=port:37565,block,services:DebugMessages,QmlDebugger,V8Debugger,QmlInspector,DebugTranslation ...

I can debug in CLion, but only c++ code (QML/JS debug in CLion is not working, meaning breakpoints dosnt work).

**Comment by fmanlou** [comment]
Yes, when I was testing, I found that Qt Creator couldn't start debugging. However, I'm not entirely sure if it's caused by GDB's Python script. Since I rarely use Qt Creator, I haven't paid much attention to it. Thank you very much for bringing up this issue. I'll try to fix it as soon as possible. It's now the Chinese New Year holiday, so if this problem turns out to be complex (I hope it's not), it might take some time for the update.

**Comment by fmanlou** [comment]
Very luckily, this issue isn't too complicated. It occurred because there was a file named `utils.py` in the gdb python scripts of qtcreator, which caused the debugging startup to fail. I'm not very familiar with Python syntax, so I simply renamed `utils.py` under `qt6printers` to `tools.py`. I tested it in vscode and qtcreator, and it worked fine. I hope this helps you.

**Comment by cezaryece** [comment]
its working!!!
